### ISSUE TITLE
Can't import RandomForest from gefs due to Numba import error

### ISSUE THREAD

**Issue by notAmine** [AlCorreia/GeFs#2]
Hello when testing out the package I ran into this error (pasted only last couple of lines)

```
    module = self._system_import(name, *args, **kwargs)
  File "/home/amine/anaconda3/envs/dsa2/lib/python3.7/site-packages/gefs/utils.py", line 4, in <module>
    from numba import jit, njit, prange, jitclass
ImportError: cannot import name 'jitclass' from 'numba' (/home/amine/anaconda3/envs/dsa2/lib/python3.7/site-packages/numba/__init__.py)

```
I had to delete the `jitclass` from 4th line of utils.py `from numba import jit, njit, prange, jitclass`

**Comment by arita37** [comment]
Numba version likely to be incorrect:
https://numba.pydata.org/numba-doc/latest/extending/high-level.html

https://numba.pydata.org/numba-doc/0.46.0/index.html

**Comment by AlCorreia** [comment]
Hello. As @arita37 mentioned, this is probably due to the numba version you are using. At some point they moved ``jitclass`` to the ``experimental`` module, so you can try ``from numba.experimental import jitclass``.

With numba 0.51, I do not get any errors, but at any rate that dependency is not needed in ``utils.py``. Thanks for pointing that out. I am updating the code to remove such unnecessary dependencies.
