### ISSUE TITLE
Got like a 1000 lines of "Previously unobserved category for variable  12" in model.classify(Xpred.iloc[:,:-1].values, classcol = -1, return_prob=True)

### ISSUE THREAD

**Issue by N950** [AlCorreia/GeFs#6]
Is this just a warning or am I giving the func the wrong inputs ??

**Comment by AlCorreia** [comment]
This warning means that during inference, a new category was observed for one of your variables. For instance, variable 12 was either 0 or 1 during training, but in your test data you also observed category 2.

This is not necessarily a problem. Inference will still run, but the model will give a very low probability (as it should) for this observation, as it has never seen that particularly instantiation of variable 12. The warning is there because this behaviour is often caused by a problem with your data.

If you do expect new categories to appear on your test data, you can either change your `ncat` to include the number of all possible classes, or just remove the warning altogether (comment out line 304 in [nodes.py](https://github.com/AlCorreia/GeFs/blob/f5725d7787149eea3886f52437cec77513e30666/gefs/nodes.py#L304)).

If you do not expect new categories, I suppose the problem is that you have not ordered your categorical variables as expected. The model assumes that categories are represented by integers, starting with zero. So if variable 12 has 3 possible categories, these must be {0, 1, 2} and not {1, 2, 3} or anything else. You can check how the data is pre-processed in the experiments in [experiments\prep.py](https://github.com/AlCorreia/GeFs/blob/f5725d7787149eea3886f52437cec77513e30666/experiments/prep.py). There is a `get_dummies` function there that takes care of that.
